# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('persons', models.IntegerField()),
                ('price', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact_info', models.TextField()),
            ],
        ),
    ]
